# -- Parametres du theme Blowfish --

colorScheme = "reitere"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = true

disableImageOptimization = false
disableTextInHeader = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = false
  showMoreLink = false
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showDraftLabel = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true
  cardView = true

[term]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
